// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJSR4T2FV9ufqVKX7R2ubwT_CvjU0yhPM',
    appId: '1:366971283695:web:0bcd957a21da497331531a',
    messagingSenderId: '366971283695',
    projectId: 'loginapp-60d75',
    authDomain: 'loginapp-60d75.firebaseapp.com',
    storageBucket: 'loginapp-60d75.appspot.com',
    measurementId: 'G-XPPWMD9FZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvpAtR1Xy6XvRiJk9SJY6NP-IoRSyn3IU',
    appId: '1:366971283695:android:02c9df3f84cac50031531a',
    messagingSenderId: '366971283695',
    projectId: 'loginapp-60d75',
    storageBucket: 'loginapp-60d75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8d6ZF-6CyOc6ojP3YwmUqEgO3QaBX-KU',
    appId: '1:366971283695:ios:3c131cda778d243f31531a',
    messagingSenderId: '366971283695',
    projectId: 'loginapp-60d75',
    storageBucket: 'loginapp-60d75.appspot.com',
    iosBundleId: 'com.example.logapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8d6ZF-6CyOc6ojP3YwmUqEgO3QaBX-KU',
    appId: '1:366971283695:ios:92ed0e82001b621b31531a',
    messagingSenderId: '366971283695',
    projectId: 'loginapp-60d75',
    storageBucket: 'loginapp-60d75.appspot.com',
    iosBundleId: 'com.example.logapp.RunnerTests',
  );
}
